- tests/test_cursor.py
I've added test for ``cursor.description`` after ``cursor.execute()``
Please review.
> add test for description after .execute

- CHANGES.txt
- aiopg/cursor.py
- docs/conf.py
- docs/core.rst
- tests/test_cursor.py
I've modified little bit ``test_iter(self)`` test:
```python
def test_iter(self):
@asyncio.coroutine
def go():
conn = yield from self.connect()
cur = yield from conn.cursor()
yield from cur.execute("SELECT * FROM tbl")
data = [(1, 'a'), (2, 'b'), (3, 'c')]
fetched_data = []
for item in cur:
fetched_data.append(item)
self.assertEquals(fetched_data, data)
self.loop.run_until_complete(go())
```
And following issue poped up.
```python
======================================================================
FAIL: test_iter (tests.test_cursor.TestCursor)
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests/test_cursor.py", line 449, in test_iter
self.loop.run_until_complete(go())
File "/usr/lib/python3.4/asyncio/base_events.py", …
```
> issue with cursor __iter__

- aiopg/sa/connection.py
- aiopg/sa/result.py
Because `SQLCompiler.result_map` API has been removed in SQLAlchemy 1.0
(sqlalchemy diff https://github.com/zzzeek/sqlalchemy/commit/9854114f578833aee49b65e440319a0ec26daab6#diff-6e10aff76d8add452655df8180dc404bL667)
> get rid of ResultProxy._result_map

- Makefile
I made a virtualenv in the "env" directory inside the project root.  Py.test picked up all the tests from the packages in the virtualenv.  This prevents that from happening.
> Specify test directory when calling py.test

- tests/test_sa_transaction.py
Engine.release is not coroutine, no need to patch it with coroutine.
> fix patched engine release in transaction tests

- README.rst
Indention was off, code contained an unused import, and was missing the `create_table` function to setup the db tables for the example. 
I'm really digging this project, so I'd hate to see other newcomers try out the example in the README and it scare them off. Cheers.
> Fixup README example for SQLAlchemy.

- aiopg/connection.py
- tests/test_connection.py
`Connection` `_conn` attribute might not be set if `__init__` crashes early
due to a psycopg error on connect.
Make sure `__del__` does not crash when this happens.
Closes #111
> Don't crash when Connection is GC'ed

- README.rst
Reverts aio-libs/aiopg#131
It breaks `python setup.py check -rms` command
> Revert "README examples with syntax highlighting"

- aiopg/connection.py
- tests/test_connection.py
Previously, the callback removal was postponed until .close() call, and
sometimes this .close() call cleared a file descriptor from a callback set
by another connection object (if the file desriptor was closed by psycopg2 when
an error occurred, and then opened again for a new connection).
The effect of this was, when making tens of parallel connections, an error in
one of them made another time out.
Now, if a psycopg2 error occurs, and the file descriptor has gone bad, the
callback is removed immediately, and the aiopg connection object 'forgets'
about this file descriptor (self._fileno = None), and doesn't try to remove
callbacks in .close().
If there were no errors, callbacks are still removed during .close() call.
Fixes #138.
> Remove callbacks from a bad file descriptor immediately

- aiopg/connection.py
- tests/test_connection.py
Also updated tests to always remove descriptors from event loop if closed. This is because the asyncio event loop under windows creates errors if the loop is run and there are closed file descriptors in the select. 
The reason that aiopg stopped working under windows (it did work until v11.0) was the recent introduction of the use of the fcntl function to determine if the filedescriptor had been closed. A more OS friendly poll on the socket has been used instead, to determine if the filedescriptor has been closed.
To run the tests under windows, the `pg_server` fixture had to be changed, as obviously docker is not available under windows. It was changed to run on a local database rather than a docker database, but these changes were not added to the pull request as they were a hack, and …
> Fixed connection to work under both windows and posix based systems

- aiopg/sa/connection.py
- tests/pep492/test_async_await.py
added support for .begin_nested() cm
In test suite teher are generally no context manager tests for `.begin()` so I did not create any for `.begin_nested()`.
Existing tests passed.
> added .begin_nested() cm support

- README.rst
GitHub supports syntax highlighting in `.rst` files with the `.. code:: <language>` mark-up. Use this to make the README.rst examples pretty.
> Enable syntax highlighting for README examples

- docs/conf.py
By default dict.get() returns None, if the key you were searching for wasn't found. Therefore, you can remove None as second argument.
> Unnecessary None as second argument

- aiopg/connection.py
- aiopg/pool.py
- aiopg/sa/engine.py
- tests/test_pool.py
Related to issue: https://github.com/aio-libs/aiopg/issues/372
Now you can do simply:
```python
db_engine = await aiopg.sa.create_engine(..., recycle=300)
```
... and then all connections which were unused last `300` seconds - will be automatically closed and re-established.
> Pool connections recycling

- aiopg/__init__.py
- aiopg/cursor.py
- aiopg/transaction.py
- aiopg/utils.py
- docs/core.rst
- examples/transaction.py
- examples/transaction_oldsyle.py
- tests/pep492/test_async_transaction.py
- tests/test_cursor.py
- tests/test_transaction.py
> Add transaction model aiopg

- aiopg/sa/result.py
- requirements.txt
Fixes #411
Related SQLAlchemy commit https://github.com/zzzeek/sqlalchemy/commit/31f80b9eaeb3c3435b7f6679b41e434478b1d11c
> Fix SQLAlchemy 1.2.0 compatibility

- requirements.txt
- setup.py
- tests/test_connection.py
- tests/test_sa_engine.py
Upgrade to psycopg2 fixes our CI:
```bash
Downloading psycopg2-2.6.2.tar.gz (376kB)
100% |████████████████████████████████| 378kB 3.4MB/s 
Complete output from command python setup.py egg_info:
running egg_info
creating pip-egg-info/psycopg2.egg-info
writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
writing pip-egg-info/psycopg2.egg-info/PKG-INFO
writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
Error: could not determine PostgreSQL version from '10.1'
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6vyhk2zm/psycopg2/
The command "pip install -Ur requirements.txt" failed and exited with 1 during .
``` …
> Update psycopg version

- aiopg/sa/engine.py
Hi,
I would like to introduce simple change. In my cases I want to use another JSON serializer, for now I need to copy whole dialect initialization code into my sources. I don't want to do this. So in PR you can find new function called `get_dialect`. Changes backward compatible, but I'm open to make any changes and improvements.
Best regards
> Added `get_dialect` func to have ability to pass `json_serializer`

- aiopg/sa/connection.py
- tests/test_sa_transaction.py
Allows transaction mode to be set on `SAConnection.begin()` method calls
> sqlalchemy adapter trx begin allow transaction_mode

- setup.py
> Rename `psycopg2` to `psycopg2-binary` to fix deprecation warning

- Makefile
- aiopg/__init__.py
- aiopg/connection.py
- aiopg/cursor.py
- aiopg/pool.py
- aiopg/sa/connection.py
- tests/conftest.py
- tests/pep492/test_async_await.py
- tests/pep492/test_sa_priority_name.py
- tests/test_connection.py
- tests/test_cursor.py
- tests/test_pool.py
- tests/test_sa_connection.py
- tests/test_sa_cursor.py
- tests/test_sa_transaction.py
- tests/test_transaction.py
Hi team.
Added `ResourceWarning` warning, if you open a new cursor in one connection, I had to edit the tests. since in many the tests cursor we did not close. Now everything passes.
I will correct the documentation in this PR https://github.com/aio-libs/aiopg/pull/534
> refactor one connect one cursore

- CHANGES.txt
The presentation of the changelog at https://aiopg.readthedocs.io/en/stable/changes.html is broken due to missing heading markdown for version 1.0.0.
This change fixes the presentation by adding the missing markup.
In addition, missing blank lines are inserted for a consistent plain text view.
> Fix changelog markup

- tests/conftest.py
It looks like fresh PG images are not able to start without `POSTGRES_HOST_AUTH_METHOD=trust` in env
> Pass POSTGRES_HOST_AUTH_METHOD=trust

- aiopg/connection.py
- aiopg/pool.py
Fix deprecation warnings where a loop argument is passed to asyncio APIs
No
https://github.com/aio-libs/aiopg/issues/622
> Fix python 3.8 warnings #622

- .github/workflows/ci.yml
- requirements.txt
- setup.py
- tests/test_async_await.py
Min supported version of psycorg is 2.8.4 because of python 3.8
> Bump psycorg and sqlalchemy, add python 3.8, 3.9 to test matrix

- aiopg/pool.py
- docs/core.rst
- tests/test_pool.py
Fixes #551 
The Pool `on_connect` handler is now called exactly once per connection, rather than on every call to `acquire`
Also, some things on your PR template checklist can't be done, as you don't have a CONTRIBUTORS.txt or a CHANGES folder?
- ~~If you provide code modification, please add yourself to `CONTRIBUTORS.txt`~~
- ~~Add a new news fragment into the `CHANGES` folder~~
> Fix on_connect multiple call on acquire

- aiopg/sa/engine.py
- tests/conftest.py
- tests/test_async_await.py
- tests/test_sa_engine.py
The goal of the PR is to actualise the fix made in #558 by @vmagamedov, but with slightly reworked tests.
Fixes #332, #665, #666 as well.
It looks like both exceptions(`psycopg2.InterfaceError` and `psycopg2.OperationalError`) could be raised, see https://github.com/aio-libs/aiopg/pull/756/checks?check_run_id=1503163697, initially only the first one was expected in the tests.
Tests are written using intermediate tcp proxy to allow disrupt a connection and cover two cases:
1. When a connection has disrupted before a request(`SELECT 1;` for instance) is executed, so rollback could not be executed. 
2. When a connection has disrupted before begin is executed.
> Fix Engine.release method to release connection in any way

- CHANGES.txt
- MAINTAINERS.txt
- aiopg/__init__.py
1. `Fix on_connect multiple call on acquire` #552
1. `Fix python 3.8` warnings #622
1. `Bump minimum psycopg version to 2.8.4` #754 
1. `Fix Engine.release method to release connection in any way` #756
> Release 1.1.0b0

- CHANGES.txt
- aiopg/__init__.py
- aiopg/utils.py
I've added missing slots to several context managers
> Added missing slots to context managers

- aiopg/connection.py
- aiopg/pool.py
- aiopg/utils.py
It looks like we are able to use loop.create_future directly, because now we supports python 3.6 and above.
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_future
> Use loop.create_future directly

- CHANGES.txt
- aiopg/__init__.py
- aiopg/pool.py
- requirements.txt
- setup.py
- tests/conftest.py
- tests/test_pool.py
PR adds timeout for the acquiring a connection from the pool.
`Pool.acquire` will raise `TimeoutError` if no connection is returned from the pool in specified timeout. 
Fixes #130, #218
> Implement timeout on acquiring connection from pool

- aiopg/connection.py
- docs/core.rst
- tests/test_async_await.py
- tests/test_connection.py
- tests/test_pool.py
> Remove blocking connection.cancel() method

- aiopg/connection.py
- aiopg/cursor.py
- aiopg/transaction.py
- tests/conftest.py
- tests/test_async_transaction.py
- tests/test_cursor.py
- tests/test_isolation_level.py
- tests/test_transaction.py
PR introduces `IsolationLevel.default` and fixes `IsolationLevel.read_comitted` as it was mentioned by @dvarrazzo.
Instead of hacking
```
with (await pool.cursor()) as cur:
cur._transaction = aiopg.Transaction(
cur, aiopg.IsolationLevel.read_committed
)
yield cur
```
PR allows to pass `IsolationLevel`
```
with (await pool.cursor(isolation_level=aiopg.IsolationLevel.read_committed)) as cur:
yield cur
```
Fixes #699
> Fix IsolationLevel.read_comitted and introduce IsolationLevel.default

- aiopg/sa/connection.py
- aiopg/transaction.py
- tests/test_sa_transaction.py
- tests/test_transaction.py
Fixes #777.
This can be caused when a query times out while running, for example, and the connection is closed as a result (as opposed to cancelling the query, since PR #570). In this case, we would rather not emit the ROLLBACK (the connection is already closed, so the transaction is over anyway), rather than raising an exception when trying to use a connection which is already closed.
I wasn't sure if it was cleaner to do this here (inside the implementation of rollback) or in the context manager of the transaction. The disadvantage of this implementation is that here we are also affecting any rollback that someone does manually, but implementing it in the context manager is awkward since it doesn't have access to the connection object, and we wouldn't have a way to set …
> Don't run ROLLBACK when the connection is closed.

- setup.py
This change prevents installation of unsupported version of SQLAlchemy
#798
> Set max supported sqlalchemy version

- aiopg/connection.py
This is fix to https://github.com/aio-libs/aiopg/issues/807
> pop loop in connection init due to backward compatibility

- aiopg/sa/connection.py
- aiopg/sa/engine.py
- requirements.txt
- setup.py
- tests/test_sa_connection.py
Fixes #798
Now in SA, there are two options for how to compile the query.
`literal_binds` and `render_postcompile`
Both options work correctly with the current code base since `aiopg` does not support executemany
https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#all-in-expressions-render-parameters-for-each-value-in-the-list-on-the-fly-e-g-expanding-parameters
Unfortunately, this solution does not support late-expanded
https://docs.sqlalchemy.org/en/14/changelog/migration_12.html#late-expanded-in-parameter-sets-allow-in-expressions-with-cached-statements
to support this feature need to rework the `_execute` method of the `SAConnection` class
> Fix compatibility with SA 1.4 for IN statement

- aiopg/sa/connection.py
- tests/test_sa_connection.py
> raise ResourceClosedError if we try to open a cursor on a closed SAConnection

- aiopg/connection.py
- aiopg/utils.py
- docs/core.rst
- examples/notify.py
- tests/test_connection.py
- tests/test_utils.py
When connection to DB is closed, any tasks pending on `await connection.notifies.get()` receives an exception, instead of hanging forever.
Now `connection.notifies.get()` can raise a psycopg2 exception, whereas before this would hang forever.
#249
* The format is `<Name> <Surname>`.
* Please keep alphabetical order, the file is sorted by names. 
* Make sure to use …
> Fix "Unable to detect disconnect when using NOTIFY/LISTEN", Closes #249

- aiopg/connection.py
- aiopg/utils.py
- tests/test_connection.py
- tests/test_utils.py
We had the following crutch to force reconnection, it was necessary before the fix #559.
```
async with connection.cursor() as cursor:
await cursor.execute(f"LISTEN {self._channel}")
while True:
try:
async with async_timeout.timeout(self._reconnect_timeout):
message = await connection.notifies.get()
yield message.payload
except asyncio.TimeoutError:
logger.info("Too long delay between notifications. We have to reconnect")
break
```
It helped to find the issue in `ClosableQueue` implementation: `ClosableQueue.get` doesn't handle cancellation well, `get loop.create_task(self._queue.get())` is not cancelled if a cancellation happens in `await asyncio.wait([get, self._close_exception], return_when=asyncio.FIRST_COMPLETED)`.
```
Task was destroyed but it is pending!
task: <Task pending …
```
> Fix ClosableQueue.get on cancellation, close it on Connection.close

- aiopg/connection.py
- aiopg/utils.py
The fix suppresses the following error via ugly hack using `.add_done_callback(lambda f: f.exception())`:
```
Future exception was never retrieved
future: <Future finished exception=OperationalError('Connection closed')>
```
Also I had to add `loop.is_closed()` to suppress this error in tests:
```
Traceback (most recent call last):
File "/Users/yurypliner/Sources/aiopg/aiopg/pool.py", line 476, in __del__
conn.close()
File "/Users/yurypliner/Sources/aiopg/aiopg/connection.py", line 995, in close
self._close()
File "/Users/yurypliner/Sources/aiopg/aiopg/connection.py", line 990, in _close
self._notifies_proxy.close(
File "/Users/yurypliner/Sources/aiopg/aiopg/utils.py", line 152, in close
self._close_event.set_exception(exception)
File …
```
> Suppress "Future exception was never retrieved"

- CHANGES.txt
- tests/conftest.py
- tests/test_cursor.py
Tests were using outdated/deprecated PostgreSQL versions. For better results tests should run over an actual PostgreSQL version.
I also had to remove some assertions in tests since they decided to phase out `oids` feature since PostgreSQL 12. See: https://stackoverflow.com/a/57022291/10650942
No. Only in tests.
* Make sure to use full sentences with correct case and …
> Update PostgreSQL versions used in tests

- docs/conf.py
Fix `make docs` command to build documentation site locally. It used to fail like this:
```
$ make doc
cd docs && rm -rf _build/html
cd docs && make html
make[1]: Entering directory '/home/br0ke/git/aiopg/docs'
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.0.3
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "/home/br0ke/git/aiopg/.env/lib64/python3.8/site-packages/sphinx/config.py", line 323, in eval_config_file
exec(code, namespace)
File "/home/br0ke/git/aiopg/docs/conf.py", line 85, in <module>
release = get_release()
File "/home/br0ke/git/aiopg/docs/conf.py", line 29, in get_release
raise RuntimeError('Cannot find version in aiopg/__init__.py')
RuntimeError: Cannot find version in …
```
> Update version regex after blackifying code

- .github/workflows/ci.yml
- aiopg/utils.py
- examples/transaction.py
- tests/test_connection.py
- tests/test_cursor.py
The project seems to use `flake8`, `mypy`, `black` & `isort` but doesn't enforce it in the CI. This PR makes it necessary for these tools to pass successfully.
I had to `# type: ignore` one type errors. At the moment I don't have a clear understanding of how to fix this issue better. The PR still adds some value because all other parts of the project will be type-checked, and no new type violations will be allowed.
No. This PR affects only maintainers and future contributors.
* `.removal`: Signifying …
> Run linters in CI

- aiopg/connection.py
the type hint for Cusor.mogrify is wrong.  It returns bytes, not str (for proof, look for the unit test test_mogrify).  This fixes the type hint, and inline doc.
> fix Cursor.mogrify type hint: it returns bytes, not str

- requirements.txt
- setup.py
Bump async_timeout
aiopg version 1.3.2 conflicts with aiohttp 3.8.0
```
The conflict is caused by:
aiohttp 3.8.0 depends on async-timeout<5.0 and >=4.0.0a3
aiopg 1.3.2 depends on async-timeout<4.0 and >=3.0
```
> Bump async_timeout to ~4.0a2

- aiopg/sa/engine.py
- requirements.txt
In version SA 1.4.38, a new argument was added to the signature of the `construct_params` method.
To avoid such a problem in the future, parameters are passed through args, kwargs.
This change is backward compatible
No
#890 Incampatible with SQLAlchemy 1.4.38 and higher 
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue …
> Fix compatibility with SA 1.4.38. Pass escape_names.

- aiopg/pool.py
- tests/test_pool.py
Fix pool size limit check for unlimited connection pools.
AS IS: acquiring a connection on a pool with `minsize=0, maxsize=0` blocks forever.
AS EXPECTED: acquiring a connection on a pool with `minsize=0, maxsize=0` returns a created connection.
These changes will allow to create a pool with settings `minsize=0, maxsize=0`.
https://github.com/aio-libs/aiopg/issues/311 - even though the `TypeError` has been fixed, it is still impossible to use a pool with `minsize=0, maxsize=0`.
* `.removal`: …
> Fix pool size limit check for unlimited pools

- .github/workflows/ci.yml
- aiopg/sa/engine.py
- aiopg/sa/result.py
- docs/index.rst
- examples/isolation_sa_transaction.py
- examples/sa.py
- examples/simple_sa_transaction.py
- examples/transaction.py
- requirements.txt
- setup.py
- tests/test_sa_connection.py
- tests/test_sa_priority_name.py
- tests/test_sa_transaction.py
Fix SQLAlchemy 2.0 compatibility
No
[897.bugfix](https://github.com/aio-libs/aiopg/issues/897)
> SQLAlchemy 2.0 compatibility

- .github/workflows/ci.yml
- aiopg/utils.py
- docs/index.rst
- docs/run_loop.rst
- setup.py
- tests/test_connection.py
It is not supported anymore.
https://endoflife.date/python
> Drop python 3.7 support
