.travis.yml
README.rst

I've added coveralls to travis config, you just need to enable this repository in coveralls panel.

add coveralls and badges

---

aiopg/connection.py
aiopg/pool.py

Same as https://github.com/aio-libs/aiomysql/issues/19

restrict __del__ method to python >=3.4.1

---

aiopg/pool.py

According to documentation, maxsize = 0 means unlimited.

Support pools with unlimited size

---

README.rst

fix for https://github.com/aio-libs/aiopg/issues/68 issue

Fix missed table create in a SQLAlchemy example

---

CONTRIBUTING.rst
README.rst

In addition to improving the English phrasing, this adds instructions
for using venv to set up the virtual environment and a mention
of the setup_test_db.sql script.  I also added a note to the README
that CONTRIBUTING explains how to set up to run the tests.
I don't know if you'll want the English edits; you use "I" in the README
notes, and applying them means it will no longer be in your "normal
voice".

English edit and some doc improvements.

---

aiopg/sa/engine.py
tests/pep492/test_async_await.py

This PR adds `async with` support for `Engine`:
```python
async with create_engine(...) as engine:
pass
```
as well as:
```python
engine = await create_engine(...)
async with engine.acquire() as conn:
conn.execute()
```

Add async with for engine

---

aiopg/cursor.py
aiopg/sa/connection.py
aiopg/sa/result.py
aiopg/sa/transaction.py
aiopg/utils.py
tests/pep492/test_async_await.py

Add more async support

---

aiopg/pool.py
tests/test_pool.py

Hi!
Pease check commit at https://github.com/aio-libs/aiopg/issues/116
Thanks

Issue 116. Remove closed connections from pool.

---

README.rst

See the [result in action here](https://github.com/WnP/aiopg/tree/patch-1#example)

README examples with syntax highlighting

---

docs/core.rst
docs/index.rst
docs/sa.rst
examples/sa.py
examples/simple_sa.py

Clarify connection pool documentation and examples

---

aiopg/sa/connection.py
aiopg/sa/result.py
tests/test_sa_types.py

As I understand it, the problem arose after was merged #55 
effects of problem #86

python types columns issues #86

---

.pyup.yml
.travis.yml
Makefile
README.rst
requirements.txt
setup.cfg

CI updates

---

docs/index.rst

spelling error

---

Makefile
tests/test_connection.py

DSN format was changed in new version

Fix psycopg2 compatibility.

---

requirements.txt
tests/conftest.py

Upgrade docker-py package from 1.10.6 to docker 2.7.0
(original package was renamed)

Upgrade docker-py from 1.10.6 to docker 2.7.0

---

aiopg/connection.py
tests/test_connection.py

added logger `asyncio.CancelledError` for statements timeout. issues  https://github.com/aio-libs/aiopg/issues/537

added logger asyncio.CancelledError for statements timeout

---

docs/core.rst

[core.rst] Fix typo

---

.github/workflows/ci.yml
CHANGES.txt
aiopg/__init__.py
setup.py

```
Checking dist/aiopg-1.1.0b0.tar.gz: FAILED
`long_description` has syntax errors in markup and would not be rendered on PyPI.
line 93: Error: Unknown target name: "#552 https://github.com/aio-libs/aiopg/pull/552".
warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
```

Fix PYPI upload

---

aiopg/__init__.py
aiopg/connection.py
aiopg/cursor.py
aiopg/pool.py
aiopg/sa/connection.py
aiopg/sa/result.py
aiopg/sa/transaction.py
aiopg/transaction.py
docs/conf.py
docs/one_cursor.rst
examples/notify.py
examples/sa.py
examples/types_field_sa.py
setup.py
tests/conftest.py
tests/test_pool.py
tests/test_sa_types.py
tests/test_transaction.py

Modernize the code to work in Python 3.6+. No external changes.
None.
None.

Modernize code to Python 3.6

---

requirements.txt

https://github.com/docker/docker-py/issues/2842

Fix CI because of broken docker package

---

README.rst

chore - fix the asyncio documents link

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Introduce the new issue forms
No.
No.

Introduce issue forms

---

examples/default_field_sa.py
examples/isolation_sa_transaction.py
examples/named_field_sa.py
examples/notify.py
examples/sa.py
examples/simple.py
examples/simple_sa.py
examples/simple_sa_transaction.py
examples/transaction.py
examples/types_field_sa.py

1. `loop.run_until_complete(go())` -> `asyncio.run(go())`
2. Do not acquire a connection from the pool for listener.

Actualise examples

---

aiopg/sa/result.py
aiopg/sa/utils.py
tests/test_cursor.py
tests/test_sa_result.py

Fix compatibility with SQLAlchemy >= 1.4.
Fixes #869.

Fix compatibility with SQLAlchemy >= 1.4

---

aiopg/sa/result.py
tests/test_sa_priority_name.py

Respect use_labels for select statement

---

aiopg/pool.py
aiopg/sa/connection.py
aiopg/sa/engine.py
aiopg/sa/result.py
aiopg/sa/transaction.py

I've add typings to enable typing hits, when somebody (include me) using this package in their projects
No any behaviour changes, only added typings

Add typings
